In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df.head()

Person ID Gender  Age            Occupation  Sleep Duration  \
0          1   Male   27     Software Engineer             6.1   
1          2   Male   28                Doctor             6.2   
2          3   Male   28                Doctor             6.2   
3          4   Male   28  Sales Representative             5.9   
4          5   Male   28  Sales Representative             5.9   

   Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                 6                       42             6   Overweight   
1                 6                       60             8       Normal   
2                 6                       60             8       Normal   
3                 4                       30             8        Obese   
4                 4                       30             8        Obese   

  Blood Pressure  Heart Rate  Daily Steps Sleep Disorder  
0         126/83          77         4200            NaN  
1         125/80          75        10000            NaN  
2         125/80          75        10000            NaN  
3         140/90          85         3000    Sleep Apnea  
4         140/90          85         3000    Sleep Apnea

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Person ID                374 non-null    int64  
 1   Gender                   374 non-null    object 
 2   Age                      374 non-null    int64  
 3   Occupation               374 non-null    object 
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64  
 6   Physical Activity Level  374 non-null    int64  
 7   Stress Level             374 non-null    int64  
 8   BMI Category             374 non-null    object 
 9   Blood Pressure           374 non-null    object 
 10  Heart Rate               374 non-null    int64  
 11  Daily Steps              374 non-null    int64  
 12  Sleep Disorder           155 non-null    object 
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB


In [22]:
df.describe()

Person ID         Age  Sleep Duration  Quality of Sleep  \
count  374.000000  374.000000      374.000000        374.000000   
mean   187.500000   42.184492        7.132086          7.312834   
std    108.108742    8.673133        0.795657          1.196956   
min      1.000000   27.000000        5.800000          4.000000   
25%     94.250000   35.250000        6.400000          6.000000   
50%    187.500000   43.000000        7.200000          7.000000   
75%    280.750000   50.000000        7.800000          8.000000   
max    374.000000   59.000000        8.500000          9.000000   

       Physical Activity Level  Stress Level  Heart Rate   Daily Steps  
count               374.000000    374.000000  374.000000    374.000000  
mean                 59.171123      5.385027   70.165775   6816.844920  
std                  20.830804      1.774526    4.135676   1617.915679  
min                  30.000000      3.000000   65.000000   3000.000000  
25%                  45.000000      4.000000   68.000000   5600.000000  
50%                  60.000000      5.000000   70.000000   7000.000000  
75%                  75.000000      7.000000   72.000000   8000.000000  
max                  90.000000      8.000000   86.000000  10000.000000

In [23]:
df.drop('Person ID', axis=1, inplace=True)

In [24]:

df['Sleep Disorder'].fillna('Normal', inplace=True)

<ipython-input-24-a08bf693a690>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sleep Disorder'].fillna('Normal', inplace=True)


In [25]:
df.isnull().sum()

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [26]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [77]:
df['Stress Level'].unique()

array([6, 8, 7, 4, 3, 5])

In [27]:
df['Occupation'].unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager'], dtype=object)

In [28]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [29]:
df['Quality of Sleep'].unique()

array([6, 4, 7, 5, 8, 9])

In [30]:
df['Blood Pressure'].unique()

array(['126/83', '125/80', '140/90', '120/80', '132/87', '130/86',
       '117/76', '118/76', '128/85', '131/86', '128/84', '115/75',
       '135/88', '129/84', '130/85', '115/78', '119/77', '121/79',
       '125/82', '135/90', '122/80', '142/92', '140/95', '139/91',
       '118/75'], dtype=object)

In [31]:
df['Sleep Disorder'].unique()

array(['Normal', 'Sleep Apnea', 'Insomnia'], dtype=object)

In [32]:
df['Sleep Disorder'].value_counts()

Sleep Disorder
Normal         219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [33]:
# prompt: saya ingin membuat kolom baru bernama sistolik dan diastolik valuenya diambil dari memisahakan value kolom Blood Pressure

# Assuming 'Blood Pressure' column has values like '120/80'
def extract_blood_pressure(bp_str):
    try:
        sistolik, diastolik = map(int, bp_str.split('/'))
        return sistolik, diastolik
    except (ValueError, AttributeError):
        return np.nan, np.nan

df[['sistolik', 'diastolik']] = df['Blood Pressure'].apply(lambda x: pd.Series(extract_blood_pressure(x)))

In [34]:
# Mengidentifikasi jenis kolom (variabel) dalam sebuah dataframe berdasarkan tipe data dan karakteristiknya

def grab_col_names(dataframe, cat_th = 10, car_th = 20): #  memisahkan kolom dalam dataset berdasarkan tipe dan karakteristiknya.

    cat_cols = [col for col in dataframe.columns if str(dataframe[col].dtypes) in ["category", "object", "bool"]] # kolom kategorikal (tipe "category", "object", "bool", atau numerik dengan unique values < cat_th).
    num_but_cat = [col for col in dataframe.columns if str(dataframe[col].dtypes) in ["int64", "float64"] and dataframe[col].nunique() < cat_th] # kolom numerik yang bertindak seperti kategorikal (berdasarkan jumlah unique values).
    cat_but_car = [col for col in dataframe.columns if str(dataframe[col].dtypes) in ["category", "object"] and dataframe[col].nunique() > car_th] # kolom kategorikal dengan unique values > car_th (high cardinality).

    cat_cols = cat_cols + num_but_cat
    cat_cols = [col for col in cat_cols if col not in cat_but_car]

    # kolom numerik murni (int64, float64) yang bukan kategorikal.
    num_cols = [col for col in dataframe.columns if str(dataframe[col].dtypes) in ["int64", "float64"]]
    num_cols = [col for col in num_cols if col not in cat_cols]

    print(f"Jumlah observasi: {dataframe.shape[0]}")
    print(f"Jumlah variabel: {dataframe.shape[1]}")
    print(f"Kolom kategorikal: {len(cat_cols)}")
    print(f"Kolom Numerik: {len(num_cols)}")
    print(f"Kategori tapi kardinal: {len(cat_but_car)}")
    print(f"Numerik tapi kategorikal: {len(num_but_cat)}")

    # mengembalikan daftar kolom yang dikelompokkan berdasarkan tipe (cat_cols, num_cols, cat_but_car).
    return cat_cols, num_cols, cat_but_car

In [35]:
cat_cols, num_cols, cat_but_car = grab_col_names(df)

Jumlah observasi: 374
Jumlah variabel: 14
Kolom kategorikal: 6
Kolom Numerik: 7
Kategori tapi kardinal: 1
Numerik tapi kategorikal: 2


In [36]:
cat_cols

['Gender',
 'Occupation',
 'BMI Category',
 'Sleep Disorder',
 'Quality of Sleep',
 'Stress Level']

In [37]:
from sklearn.preprocessing import LabelEncoder
import joblib

cat_cols = ['Gender','Occupation','BMI Category','Sleep Disorder']
add_cols = ['Quality of Sleep','Stress Level']

# Buat encoder untuk setiap kolom kategorikal dan simpan dengan nama kolom
for col in cat_cols:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])
    joblib.dump(encoder, f'{col}_encoder.joblib')  # Simpan dengan nama berdasarkan kolom

data_final = pd.concat([df[num_cols], df[cat_cols],df[add_cols]], axis=1)

In [38]:
data_final.head()

Age  Sleep Duration  Physical Activity Level  Heart Rate  Daily Steps  \
0   27             6.1                       42          77         4200   
1   28             6.2                       60          75        10000   
2   28             6.2                       60          75        10000   
3   28             5.9                       30          85         3000   
4   28             5.9                       30          85         3000   

   sistolik  diastolik  Gender  Occupation  BMI Category  Sleep Disorder  \
0       126         83       1           9             3               1   
1       125         80       1           1             0               1   
2       125         80       1           1             0               1   
3       140         90       1           6             2               2   
4       140         90       1           6             2               2   

   Quality of Sleep  Stress Level  
0                 6             6  
1                 6             8  
2                 6             8  
3                 4             8  
4                 4             8

In [39]:
cat_cols, num_cols, cat_but_car = grab_col_names(data_final)

Jumlah observasi: 374
Jumlah variabel: 13
Kolom kategorikal: 5
Kolom Numerik: 8
Kategori tapi kardinal: 0
Numerik tapi kategorikal: 5


In [40]:
# data_final = pd.concat([data_final[num_cols], data_final[cat_cols]], axis=1)
data_final.head()

Age  Sleep Duration  Physical Activity Level  Heart Rate  Daily Steps  \
0   27             6.1                       42          77         4200   
1   28             6.2                       60          75        10000   
2   28             6.2                       60          75        10000   
3   28             5.9                       30          85         3000   
4   28             5.9                       30          85         3000   

   sistolik  diastolik  Gender  Occupation  BMI Category  Sleep Disorder  \
0       126         83       1           9             3               1   
1       125         80       1           1             0               1   
2       125         80       1           1             0               1   
3       140         90       1           6             2               2   
4       140         90       1           6             2               2   

   Quality of Sleep  Stress Level  
0                 6             6  
1                 6             8  
2                 6             8  
3                 4             8  
4                 4             8

In [41]:
df['Sleep Disorder'].unique()

array([1, 2, 0])

In [42]:
data_final['Sleep Disorder'].unique()

array([1, 2, 0])

In [43]:
data_final['Sleep Disorder'].value_counts()

Sleep Disorder
1    219
2     78
0     77
Name: count, dtype: int64

In [44]:
from sklearn.model_selection import train_test_split

X = data_final.drop(columns=['Sleep Disorder'])
y = data_final['Sleep Disorder']

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [65]:
X_train

Age  Sleep Duration  Physical Activity Level  Heart Rate  Daily Steps  \
212   43             7.8                       90          70         8000   
366   59             8.1                       75          68         7000   
327   53             8.5                       30          65         5000   
251   45             6.8                       30          65         6000   
314   52             8.4                       30          65         5000   
..   ...             ...                      ...         ...          ...   
119   37             7.2                       60          68         7000   
297   50             6.1                       90          75        10000   
197   43             6.5                       45          72         6000   
47    31             7.8                       75          70         8000   
200   43             6.5                       45          72         6000   

     sistolik  diastolik  Gender  Occupation  BMI Category  Quality of Sleep  \
212       130         85       1           2             0                 8   
366       140         95       0           5             3                 9   
327       125         80       0           2             0                 9   
251       135         90       0          10             3                 7   
314       125         80       0           2             0                 9   
..        ...        ...     ...         ...           ...               ...   
119       115         75       0           0             0                 8   
297       140         95       0           5             3                 6   
197       130         85       1           7             3                 6   
47        120         80       1           1             0                 7   
200       130         85       1           7             3                 6   

     Stress Level  
212             5  
366             3  
327             3  
251             6  
314             3  
..            ...  
119             4  
297             8  
197             7  
47              6  
200             7  

[299 rows x 12 columns]

In [66]:
X_test.head()

Age  Sleep Duration  Physical Activity Level  Heart Rate  Daily Steps  \
243   44             6.5                       45          65         6000   
254   45             6.5                       45          65         6000   
290   50             6.0                       90          75        10000   
371   59             8.1                       75          68         7000   
244   44             6.3                       45          72         6000   

     sistolik  diastolik  Gender  Occupation  BMI Category  Quality of Sleep  \
243       135         90       0          10             3                 7   
254       135         90       0          10             3                 7   
290       140         95       0           5             3                 6   
371       140         95       0           5             3                 9   
244       130         85       1           7             3                 6   

     Stress Level  
243             4  
254             4  
290             8  
371             3  
244             7

In [75]:
#bikin model decision tree
from sklearn .metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
dtc = DecisionTreeClassifier(
    ccp_alpha=0.0, class_weight=None, criterion='entropy', max_features=None, max_leaf_nodes=None,max_depth=3,
    min_impurity_decrease=0.0, min_samples_leaf=3,
    min_samples_split=3, min_weight_fraction_leaf=0.0,
    random_state=42, splitter='best'
)

model = dtc.fit(X_train, y_train)
dtc_acc = accuracy_score(y_test, dtc.predict(X_test))
print(f"akurasi data training = {accuracy_score(y_train, dtc.predict(X_train))}")
print(f"akurasi data testing = {dtc_acc} \n")

print(f"confusion matrix : \n{confusion_matrix(y_test, dtc.predict(X_test))}\n")
confusion = confusion_matrix(y_test, dtc.predict(X_test))

y_pred_dtc = dtc.predict(X_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dtc))

# Menampilkan laporan klasifikasi
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dtc))

akurasi data training = 0.8929765886287625
akurasi data testing = 0.8933333333333333 

confusion matrix : 
[[13  0  2]
 [ 2 39  3]
 [ 1  0 15]]

Decision Tree Accuracy: 0.8933333333333333

Classification Report:

              precision    recall  f1-score   support

           0       0.81      0.87      0.84        15
           1       1.00      0.89      0.94        44
           2       0.75      0.94      0.83        16

    accuracy                           0.89        75
   macro avg       0.85      0.90      0.87        75
weighted avg       0.91      0.89      0.90        75



In [76]:
joblib.dump(dtc, 'model.joblib')

['model.joblib']

In [69]:
from sklearn .metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

#Menggunakan algoritme Decision Tree Classifier untuk melakukan klasifikasi.
dt = DecisionTreeClassifier(random_state=42)
#Melatih Model | X_train: Fitur pada data pelatihan. | y_train: Label target pada data pelatihan.
dt.fit(X_train, y_train)
#Membuat Prediksi | X_test: Fitur pada data uji. | Hasil prediksi disimpan dalam variabel y_pred_dt.
y_pred_dt = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

# Menampilkan laporan klasifikasi
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.92

Classification Report:

              precision    recall  f1-score   support

           0       0.74      0.93      0.82        15
           1       1.00      0.95      0.98        44
           2       0.93      0.81      0.87        16

    accuracy                           0.92        75
   macro avg       0.89      0.90      0.89        75
weighted avg       0.93      0.92      0.92        75



In [70]:

import joblib # Import library untuk menyimpan model

joblib.dump(dt, 'decision_tree_model.joblib')


['decision_tree_model.joblib']